name: TODO
description: TODO
author: Ghalactic
inputs:
  token:
    description: >-
      The GitHub token to use when TODO.
    default: ${{ github.token }}
branding:
  icon: TODO
  color: TODO
runs:
  using: node24
  main: dist/main.js
